config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  scope '/tools' do
    scope '/admin' do
      resources :users, only: [:new, :create, :index, :edit, :update, :destroy]
      resources :options, only: [:new, :create]
      scope '/users' do
        post :sync, controller: :users, as: :users_sync
        get :search, controller: :users
        get :autocomplete, controller: :users
        # same => get "/search" => "users#search", as: :search
      end
    end
  end
  get "/" => redirect("/tools/admin/users")

end

app/models/ad_group.rb
class AdGroup < ActiveLdap::Base
  ldap_mapping :dn_attribute => 'sAMAccountName', :prefix => '', :classes => ['group']
  has_many :members, :wrap => 'member', :class_name => 'AdUser', :primary_key => 'distinguishedName'
end

app/models/ad_ou.rb
class AdOu < ActiveLdap::Base
  ldap_mapping  :dn_attribute => 'OU', :prefix => '', :classes => ['organizationalUnit']
end

app/models/ad_user.rb
class AdUser < ActiveLdap::Base
  ldap_mapping :dn_attribute => 'sAMAccountName', :prefix => '', :classes => ['person', 'user']
  belongs_to :groups, :class_name => 'AdGroup', :many => 'member', :primary_key => 'distinguishedName'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/option.rb
class Option < ApplicationRecord
  has_many :user_options
  has_many :users, through: :user_options
  validates :name, presence: true, uniqueness: true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  ransack_alias :user, :username_or_first_name_or_last_name
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # :registerable, :recoverable, :rememberable
  devise :database_authenticatable, :trackable, :validatable, :timeoutable
  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login

  before_validation(on: :create) do
    self.email = "#{self.username}@pbna.intra" if self.email.blank? || self.email == 'ennov@bordeauxnord.com'
  end
  validates :username, :presence => true, :uniqueness => { :case_sensitive => false }
  validates_format_of :username, with: /^[^@]*$/, :multiline => true
  validate :validate_username
  has_many :user_options, dependent: :destroy, inverse_of: :user
  accepts_nested_attributes_for :user_options, allow_destroy: true,
                                reject_if: ->(attrs) { attrs['value'].blank? }
  has_many :options, through: :user_options

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  def first_name_if_exist
    # return first_name if exist and different of username
    return first_name unless username == first_name
  end

  def last_name_if_exist
    # return last_name if exist and different of username
    return last_name unless username == last_name
  end

  def options_values
    options_values = {}
    options.each do |option|
      options_values[option.name] = UserOption.find_by(user_id: self.id, option_id: option.id).value
    end
    options_values
  end
end

app/models/user_option.rb
require 'encrypted_coder'

class UserOption < ApplicationRecord
  serialize :value, EncryptedCoder.new
  belongs_to :user
  belongs_to :option
  validates :option, uniqueness: { scope: :user }
  validates :value, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  add_flash_types :sync_msg
  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController

  def new
    @option = Option.new
  end

  def create
    @option = Option.new(option_params)
    if @option.save
      redirect_to users_path
    else
      render :new
    end
  end

  private

  def option_params
    params.require(:option).permit(:name)
  end

end

app/controllers/user_options_controller.rb
class UserOptionsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :force_json, only: :autocomplete
  before_action :set_user, only: [:edit, :update, :destroy]

  def index
    @users = User.last(12).reverse
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.password = ENV['DEFAULT_PASSWORD']
    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to users_path
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  def sync
    @ldap = LdapService.new.users_sync
    flash[:sync_msg] = @ldap
    redirect_to users_path
  end

  def autocomplete
    @users = User.ransack(user_cont: params[:q]).result(distinct: true).limit(10)
  end

  def search
    # Do not display all users if empty search...
    if params[:q] == ''
      redirect_to users_path
      return
    else params[:q]
      @users = User.ransack(user_cont: params[:q]).result(distinct: true)
      render :index
    end
  end

  private

  def force_json
    request.format = :json
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :first_name, :last_name, :email, user_options_attributes: [:option_id, :id, :value, :_destroy])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/options/new.html.erb
<h1>Ajouter une option utilisateur</h1>

<%= simple_form_for @option do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div>
    <strong>
      <%= pluralize(object.errors.count, 'error') %> were found
    </strong>

    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>
<% if sync_msg %>
<div class="alert alert-success alert-dismissible" role="alert" style="color:black">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <strong><%= sync_msg %></strong>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to users_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Synchro AD", users_sync_path, method: :post, data: { disable_with: "Please wait..." }, class: "navbar-wagon-item navbar-wagon-link" %>

      <%= link_to "Manage Options", new_option_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <%= link_to 'Créer un user', new_user_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "default_avatar", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to users_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Synchro AD", users_sync_path, method: :post, data: { disable_with: "Please wait..." }, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/users/_card.html.erb
<div class="col-xs-12 col-sm-6 col-lg-4">
  <div class="admin-user-card">
    <div class="admin-user-card__id">
      <div class="admin-user-card__avatar">
        <%= image_tag("default_avatar.jpg", alt: "Default Avatar") %>
      </div>
      <div class="admin-user-card__infos">
        <p><b><%= user.first_name_if_exist %>
          <%= user.last_name_if_exist %></b></p>
        <p><i><%= user.email  %></i> </p>
        <p>Username : <b><%= user.username %></b></p>
      </div>
    </div>

    <div class="admin-user-card__options">
      <ul>
        <% user.options_values.each do |option| %>
        <li><%= option[0] %> : <%= option[1] %></li>
        <% end %>
      </ul>
    </div>

    <%= link_to "Suppr", user_path(user), method: :delete, data: {confirm: " L'utilisateur '#{user.username}' sera supprimé de la BDD, etes vous sur ?"}, class: "btn btn-danger admin-user-card__delete-btn"  %>

    <%= form_with url: edit_user_path(user), local: true, method: :get do |form| %>
      <%= form.button "Edit", class: "btn btn-default admin-user-card__edit-btn" %>
    <% end %>

  </div>
</div>

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= render 'shared/errors', object: @user %>

  <%= f.input :username %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email %>

  <h3>Options</h3>
  <div id='user_options'>
    <%= f.simple_fields_for :user_options do |user_option| %>
      <%= render 'user_option_fields', f: user_option %>
    <% end %>

    <div class="links">
      <%= link_to_add_association 'Ajouter une option', f, :user_options %>
    </div>
  </div>

    <%= f.submit %>
<% end %>

app/views/users/_user_card.html.erb
<div class="col-xs-12 col-sm-6 col-lg-4">
  <div class="admin-user-card">
    <div class="admin-user-card__id">
      <div class="admin-user-card__avatar">
        <%= image_tag("default_avatar.jpg", alt: "Default Avatar") %>
      </div>
      <div class="admin-user-card__infos">
        <p><b><%= user.first_name_if_exist %>
         <%= user.last_name_if_exist %></b></p>
        <p><i><%= user.email  %></i> </p>
        <p>Username : <b><%= user.username %></b></p>
      </div>
    </div>

    <div class="admin-user-card__options">
      <ul>
        <% user.options_values.each do |option| %>
        <li><%= option[0] %> : <%= option[1] %></li>
        <% end %>
      </ul>
    </div>

    <div class="admin-user-card__edit-btn">
      <button name="button" type="Edit" class="btn btn-default">Edit</button>
    </div>

  </div>
</div>

app/views/users/_user_option_fields.html.erb
<div class='nested-fields'>
  <%= f.association :option, label: "Option", collection: Option.all.order('name') %>
  <%= f.input :value %>
  <%= link_to_remove_association "Supprimer l'option", f %>
</div>

app/views/users/edit.html.erb
<h1>Editer un utilisateur</h1>

<%= render partial: "form", locals: {user: @user} %>

app/views/users/index.html.erb
<div class="jumbotron jumbotron-fluid text-center">
  <div class="container">
    <h1>Admins tools - USERS</h1>
    <p>Accés restreint !!</p>
  </div>
</div>

<div class="wrapper">

  <div class="container">
    <div class="row admin-user-search d-flex">
      <%= form_with url: search_path, local: true, method: :get, class: "form-inline text-center admin-user-search__form" do |form| %>
        <%= form.text_field :q, placeholder: "Entrer un nom d'utilisateur", data: { behavior: "autocomplete" }, class: "form-control text-center admin-user-search__field" %>
        <%= form.button "Recherche", class: "btn btn-default admin-user-search__btn" %>
      <% end %>
    </div>
  </div>

  <div class="container-fluid">
    <div class="row">
      <%= render partial: "card", collection: @users, as: :user %>
    </div>
  </div>

</div>

<% content_for(:after_js) do %>
  <script>

      $input = $("[data-behavior='autocomplete']")

      var options = {
        theme: "blue-light",
        getValue: "username",
        url: function(phrase) {
          return "/tools/admin/users/autocomplete.json?q=" + phrase;
        },
        list: {
          maxNumberOfElements: 10,
            onChooseEvent: function() {
              $('.admin-user-search__form').submit()
            }
        },
        template: {
          type: "custom",
          method: function(value, item) {
            return value + " <i>(" + item.first_name + " " + item.last_name + " )</i>"
          }
        },
        highlightPhrase: false,
      }

      $input.easyAutocomplete(options)

  </script>
<% end %>

<!-- // Try with autocomplete from Jquery UI
    // $('#term').autocomplete({
    //   source : function(request, response){
    //   // les deux arguments représentent les données nécessaires au plugin
    //     $.ajax({
    //       url : '/tools/admin/users', // on appelle le script JSON
    //       dataType : 'json', // on spécifie bien que le type de données est en JSON
    //       data : {
    //         name: request.term
    //       },
    //       success : function(data){
    //         response($.map(data, function(item){
    //            return {
    //             label: item.name
    //           };
    //         }));
    //       }
    //     });
    //   }
    // });

// Try with select2
    // var $eventSelect = $('#term').select2({
    //   ajax: {
    //     url: '/tools/admin/users',
    //     data: function(params) {
    //       return {
    //         term: params.term
    //       };
    //     },
    //     dataType: 'json',
    //     delay: 100,
    //     processResults: function(data, params) {
    //       return {
    //         results: $.map(data, function(el) {
    //           return {
    //             id: el.username,
    //             name: el.username + " (" + el.firstname + " " + el.lastname + ")",
    //           };
    //         })
    //       };
    //     },
    //     cache: true
    //   },
    //   tags: true,
    //   theme: "bootstrap",
    //   escapeMarkup: function(text) {
    //     return text;
    //   },
    //   minimumInputLength: 2,
    //   templateResult: function(item) {
    //     return item.name;
    //   },
    //   templateSelection: function(item) {
    //     return item.name;
    //   }
    // });
    // $eventSelect.on("select2:select", function() {
    //    $(this).parents('form').submit();
    // }); -->

app/views/users/new.html.erb
<h1>Créer un nouvel utilisateur</h1>

<%= render 'form' %>